In [1]:
import tensorflow as tf
print(tf.executing_eagerly())

True


In [2]:
a = 1
b = 2
c = tf.math.add(a, b)
print(c)

tf.Tensor(3, shape=(), dtype=int32)


In [3]:
c.numpy()

np.int32(3)

# 3-1 **스칼라(Scalar)**

In [16]:
import tensorflow as tf

# 스칼라 정의하기
a = tf.constant(1)
b = tf.constant(2)

print('---------------------------------------------------')

# 정수 1과 2는 0차원 텐서인 스칼라로 저장됨(shape=() : 0차원, dtype=int32 : 32비트 정수형)
print("a:", a)
print("b:", b)
print('---------------------------------------------------')

# 랭크 확인하기
print(tf.rank(a))
print('---------------------------------------------------')

# 자료형 변환
# 텐서플로 딥러닝 연산에서는 float32를 숫자형 데이터를 나타내는 기본 자료형으로 사용함
a = tf.cast(a, tf.float32)
b = tf.cast(b, tf.float32)
print(a.dtype)
print(b.dtype)
print('---------------------------------------------------')

# 덧셈, add()
c = tf.math.add(a, b)
print("result:", c)
print("rank:", tf.rank(c))
print('---------------------------------------------------')

# 뺄셈, subtract()
print(tf.math.subtract(a, b))
print('---------------------------------------------------')

# 곱셈, multiply()
print(tf.math.multiply(a, b))
print('---------------------------------------------------')

# 나눗셈, divide()
print(tf.math.divide(a, b))
print('---------------------------------------------------')

# 나눗셈(나머지), mod()
print(tf.math.mod(a, b))
print('---------------------------------------------------')

# 나눗셈(몫), floordiv()
print(tf.math.floordiv(a, b))
print('---------------------------------------------------')

---------------------------------------------------
a: tf.Tensor(1, shape=(), dtype=int32)
b: tf.Tensor(2, shape=(), dtype=int32)
---------------------------------------------------
tf.Tensor(0, shape=(), dtype=int32)
---------------------------------------------------
<dtype: 'float32'>
<dtype: 'float32'>
---------------------------------------------------
result: tf.Tensor(3.0, shape=(), dtype=float32)
rank: tf.Tensor(0, shape=(), dtype=int32)
---------------------------------------------------
tf.Tensor(-1.0, shape=(), dtype=float32)
---------------------------------------------------
tf.Tensor(2.0, shape=(), dtype=float32)
---------------------------------------------------
tf.Tensor(0.5, shape=(), dtype=float32)
---------------------------------------------------
tf.Tensor(1.0, shape=(), dtype=float32)
---------------------------------------------------
tf.Tensor(0.0, shape=(), dtype=float32)
---------------------------------------------------


# 3-2 **벡터(Vector)**

In [26]:
import tensorflow as tf
import numpy as np

# 1차원 배열 정의

# 파이썬 리스트 활용
py_list = [10., 20., 30.]
# 넘파이 배열 활용
num_arr = np.array([10., 10., 10.])
print('---------------------------------------------------')

# 텐서 변환
vec1 = tf.constant(py_list, dtype=tf.float32)
vec2 = tf.constant(num_arr, dtype=tf.float32)
print('---------------------------------------------------')

# 텐서 출력, shap(3,) : 1개의 축에 3개의 원소
print("vec1:", vec1)
print("vec2:", vec2)
print('---------------------------------------------------')

# 랭크 확인
print(tf.rank(vec1))
print(tf.rank(vec2))
print('---------------------------------------------------')

# 덧셈 함수
add1 = tf.math.add(vec1, vec2)
print("result:", add1)
print("rank:", tf.rank(add1))
print('---------------------------------------------------')

# 파이썬 덧셈 연산자
add2 = vec1 + vec2
print("result:", add2)
print("rank:", tf.rank(add2))
print('---------------------------------------------------')

# tf.math 모듈 함수
print(tf.math.subtract(vec1, vec2))
print(tf.math.multiply(vec1, vec2))
print(tf.math.divide(vec1, vec2))
print(tf.math.mod(vec1, vec2))
print(tf.math.floordiv(vec1, vec2))
print('---------------------------------------------------')

# 파이썬 연산자
print(vec1 - vec2)
print(vec1 * vec2)
print(vec1 / vec2)
print(vec1 % vec2)
print(vec1 // vec2)
print('---------------------------------------------------')

# 합계 구하기
print(tf.reduce_sum(vec1))
print(tf.reduce_sum(vec2))
print('---------------------------------------------------')

# 거듭제곱
print(tf.math.square(vec1))
print('---------------------------------------------------')

# 거듭제곱(파이썬 연산자)
print(vec1**2)
print('---------------------------------------------------')

# 제곱근
print(tf.math.sqrt(vec2))
print('---------------------------------------------------')

# 제곱근(파이썬 연산자)
print(vec2**0.5)
print('---------------------------------------------------')

# 브로드캐스팅 연산
print(vec1 + 1)
print('---------------------------------------------------')

---------------------------------------------------
---------------------------------------------------
vec1: tf.Tensor([10. 20. 30.], shape=(3,), dtype=float32)
vec2: tf.Tensor([10. 10. 10.], shape=(3,), dtype=float32)
---------------------------------------------------
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
---------------------------------------------------
result: tf.Tensor([20. 30. 40.], shape=(3,), dtype=float32)
rank: tf.Tensor(1, shape=(), dtype=int32)
---------------------------------------------------
result: tf.Tensor([20. 30. 40.], shape=(3,), dtype=float32)
rank: tf.Tensor(1, shape=(), dtype=int32)
---------------------------------------------------
tf.Tensor([ 0. 10. 20.], shape=(3,), dtype=float32)
tf.Tensor([100. 200. 300.], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
------------------------------------------

# 3-3 **행렬(Matrix)**

In [37]:
# 라이브러리 불러오기
import tensorflow as tf

# 2차원 배열 정의
list_of_list = [[10,20],[30,40]]

# 텐서 변환 - constant 함수에 2차원 배열 입력
mat1 = tf.constant(list_of_list)

# 랭크 확인
print("rank:", tf.rank(mat1))
print('---------------------------------------------------')

# 1차원 벡터 정의
vec1 = tf.constant([1, 0])
vec2 = tf.constant([-1, 2])

# 텐서 변환 - stack 함수로 1차원 배열을 위아래로 쌓기
mat2 = tf.stack([vec1,vec2])

# 랭크 확인
print("rank:", tf.rank(mat2))

# 텐서 출력하기
print("mat2:", mat2)
print('---------------------------------------------------')

# element-by-element 연산
element_mul = tf.math.multiply(mat1, mat2)
print("result:", element_mul)
print("rank:", tf.rank(element_mul))

# 브로드캐스팅 연산
element_bc = tf.math.multiply(mat1, 3)
print("result:", element_bc)
print("rank:", tf.rank(element_bc))

# 행렬곱 연산
mat_mul = tf.matmul(mat1, mat2)
print("result:", mat_mul)
print("rank:", tf.rank(mat_mul))

# 덧셈 연산
add1 = tf.math.add(mat1, mat2)
print("result:", add1)
print("rank:", tf.rank(add1))

# 덧셈 연산자
add2 = mat1 + mat2
print("result:", add2)
print("rank:", tf.rank(add2))

# 텐서를 넘파이로 변환
np_arr = mat_mul.numpy()
print(type(np_arr))
print(np_arr)

rank: tf.Tensor(2, shape=(), dtype=int32)
---------------------------------------------------
rank: tf.Tensor(2, shape=(), dtype=int32)
mat2: tf.Tensor(
[[ 1  0]
 [-1  2]], shape=(2, 2), dtype=int32)
---------------------------------------------------
result: tf.Tensor(
[[ 10   0]
 [-30  80]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)
result: tf.Tensor(
[[ 30  60]
 [ 90 120]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)
result: tf.Tensor(
[[-10  40]
 [-10  80]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)
result: tf.Tensor(
[[11 20]
 [29 42]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)
result: tf.Tensor(
[[11 20]
 [29 42]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)
<class 'numpy.ndarray'>
[[-10  40]
 [-10  80]]
---------------------------------------------------
---------------------------------------------------
---------------------------------------------

# 3-4 **고차원 텐서(Tensor)**

In [41]:
# 라이브러리 불러오기
import tensorflow as tf
import numpy as np

# 2차원 배열 정의
mat1 = [[1,2,3,4],
        [5,6,7,8]]

mat2 = [[9,10,11,12],
        [13,14,15,16]]

mat3 = [[17,18,19,20],
        [21,22,23,24]]


# 텐서 변환 - constant 함수에 3차원 배열 입력
tensor1 = tf.constant([mat1,mat2,mat3])

# 랭크 확인
print("rank:", tf.rank(tensor1))

# 텐서 출력
print("tensor1:", tensor1)

# 텐서 변환
tensor2 = tf.stack([mat1,mat2,mat3])

# 랭크 확인
print("rank:", tf.rank(tensor2))

# 텐서 출력
print("tensor2:", tensor2)
print('---------------------------------------------------')

# 1차원 배열 정의
vec1 = [1,2,3,4]
vec2 = [5,6,7,8]
vec3 = [9,10,11,12]
vec4 = [13,14,15,16]
vec5 = [17,18,19,20]
vec6 = [21,22,23,24]

# 1차원 배열을 원소로 갖는 2차원 배열 정의
arr = [[vec1,vec2],
       [vec3,vec4],
       [vec5,vec6]]

# 텐서 변환
tensor3 = tf.constant(arr)

# 랭크 확인
print("rank:", tf.rank(tensor3))

# 텐서 출력
print("tensor3:", tensor3)
print('---------------------------------------------------')

# 랭크-4 텐서 만들기
tensor4 = tf.stack([tensor1,tensor2])

# 랭크 확인
print("rank:", tf.rank(tensor4))

# 텐서 출력
print("tensor4:", tensor4)

rank: tf.Tensor(3, shape=(), dtype=int32)
tensor1: tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)
rank: tf.Tensor(3, shape=(), dtype=int32)
tensor2: tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)
---------------------------------------------------
rank: tf.Tensor(3, shape=(), dtype=int32)
tensor3: tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)
---------------------------------------------------
rank: tf.Tensor(4, shape=(), dtype=int32)
tensor4: tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]]]


 [[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]]]], shape=(2, 3, 2, 4), dtype=int

# 04 **인덱싱(Indexing)**

In [52]:
# 텐서플로 불러오기
import tensorflow as tf

# 벡터 정의
vec = tf.constant([10,20,30,40,50])
print(vec)
print(vec[0])
print(vec[-1])
print(vec[:3])
print('---------------------------------------------------')

# 행렬 정의
mat = tf.constant([[10,20,30],
                  [40,50,60]])
print(mat)
print(mat[0,:])
print(mat[:,1])
print(mat[:,:])
print('---------------------------------------------------')

# 랭크-3 텐서 정의
tensor = tf.constant([
    [[10,20,30],
     [40,50,60]],
     [[-10,-20,-30],
     [-40,-50,-60]],
    ])
print(tensor)
print(tensor[0,:,:])
print(tensor[:,:2,:2])

tf.Tensor([10 20 30 40 50], shape=(5,), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(50, shape=(), dtype=int32)
tf.Tensor([10 20 30], shape=(3,), dtype=int32)
tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)
tf.Tensor([10 20 30], shape=(3,), dtype=int32)
tf.Tensor([20 50], shape=(2,), dtype=int32)
tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[[ 10  20  30]
  [ 40  50  60]]

 [[-10 -20 -30]
  [-40 -50 -60]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)


# 05 **형태 변환(tf.reshape())**

In [59]:
# 텐서플로 불러오기
import tensorflow as tf

# 랭크-1 텐서 정의
tensor = tf.constant(range(0,24))
print(tensor)
print('---------------------------------------------------')

# (3, 8) 형태의 행렬로 변환
tensor1 = tf.reshape(tensor,[3, 8])
print(tensor1)
print('---------------------------------------------------')

# (3, 8) 형태의 행렬을 (6, 4) 구조의 행렬(tensor2)로 변환
# [-1,4] : [상관없음,4열] 이므로 24개의 원소를 행렬로 변환 시 자동으로 [6,4]로 변환됨
tensor2 = tf.reshape(tensor1, [-1,4])
print(tensor2)
print('---------------------------------------------------')

# (6,4) 형태의 행렬을 (24,) 형태의 1차원 벡터(tensor3)로 변환
tensor3 = tf.reshape(tensor2, [-1])
print(tensor3)
print('---------------------------------------------------')

# (24,) 형태의 1차원 벡터(tensor3)를 (2,3,4) 형태의 랭크-3 텐서(tensor4)로 변환 (-1 사용)
tensor4 = tf.reshape(tensor3, [-1,3,4])
print(tensor4)
print('---------------------------------------------------')

# (2,3,4) 형태의 랭크-3 텐서(tensor4)를 (3,2,4) 형태의 랭크-3 텐서(tensor5)로 변환
tensor5 = tf.reshape(tensor4, [3,2,4])
print(tensor5)
print('---------------------------------------------------')

# (3,2,4) 형태의 랭크-3 텐서(tensor5)를 (3,2,2,2) 형태의 랭크-4 텐서(tensor6)로 변환
tensor6 = tf.reshape(tensor5, [3,2,2,2])
print(tensor6)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)
tf.Tensor(
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]], shape=(3, 8), dtype=int32)
tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]], shape=(6, 4), dtype=int32)
tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)
---------------------------------------------------
tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int32)
---------------------------------------------------
tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]], shape=(3, 2, 4), dtype=int32)
---------------------------------------------------
tf.Tensor(
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]



# 06 **변수(tf.Variable)**

In [69]:
# 텐서플로 불러오기
import tensorflow as tf

# 텐서 정의
tensor1 = tf.constant([[0,1,2],
                      [3,4,5]])
print(tensor1)
print('---------------------------------------------------')

# 텐서를 Variable 함수에 입력하면 텐서플로 변수가 생성
tensor_var1 = tf.Variable(tensor1)
print(tensor_var1)
print('---------------------------------------------------')

# 텐서플로 변수의 속성 값
print("이름:", tensor_var1.name)
print("크기:", tensor_var1.shape)
print("자료형:", tensor_var1.dtype)
print("배열:", tensor_var1.numpy())
print('---------------------------------------------------')

# assign() 메소드로 텐서플로 변수에 데이터 할당
tensor_var1.assign([[1,1,1],
                    [2,2,2]])
print(tensor_var1)
print('---------------------------------------------------')

# convert_to_tensor() 함수로 텐서플로 변수를 텐서로 변환(이후 상수화)
tensor2 = tf.convert_to_tensor(tensor_var1)
print(tensor2)
print('---------------------------------------------------')

# 텐서플로 변수는 name 속성을 가지므로 원하는 이름을 지정가능.
# 출력 결과가 New Name:0 인 이유는 해당 텐서가 연산의 첫 번째 출력값이기 때문임
tensor_var2 = tf.Variable(tensor2, name='New Name')
print(tensor_var2.name)
print('---------------------------------------------------')

# 텐서플로 변수도 텐서 연산과 동일하게 연산자 또는 함수를 사용하여 연산을 처리 가능
# 이때 텐서플로 변수가 저장하고 있는 텐서 값을 사용
tensor_var1 + tensor_var2

tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32)
---------------------------------------------------
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]], dtype=int32)>
---------------------------------------------------
이름: Variable:0
크기: (2, 3)
자료형: <dtype: 'int32'>
배열: [[0 1 2]
 [3 4 5]]
---------------------------------------------------
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2]], dtype=int32)>
---------------------------------------------------
tf.Tensor(
[[1 1 1]
 [2 2 2]], shape=(2, 3), dtype=int32)
---------------------------------------------------
New Name:0
---------------------------------------------------


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 2, 2],
       [4, 4, 4]], dtype=int32)>

# 07 **자동 미분(Automatic Differentiation)**

In [79]:
# tf.random 모듈의 Generator
# 라이브러리 불러오기
import tensorflow as tf

# y = 3x - 2 선형 관계를 갖는 데이터셋 생성
g = tf.random.Generator.from_seed(2020)
X = g.normal(shape=(10,))
Y = 3 * X - 2

print('X: ', X.numpy())
print('Y: ', Y.numpy())
print('---------------------------------------------------')

# MSE(평균제곱오차, mean squared error)를 계산하는 cal_mse 손실함수를 정의

# Loss 함수 정의
def cal_mse(X,Y,a,b):

  Y_pred = a * X + b
  squared_error = (Y_pred - Y) ** 2
  mean_squared_error = tf.reduce_mean(squared_error)

  return mean_squared_error

# tf.GradientTape로 자동 미분 과정을 기록

a = tf.Variable(0.0)
b = tf.Variable(0.0)

EPOCHS = 200

for epoch in range(1, EPOCHS + 1):
  with tf.GradientTape() as tape:
    mse = cal_mse(X,Y,a,b)

  grad = tape.gradient(mse, {'a': a, 'b': b})
  d_a, d_b = grad['a'], grad['b']

  a.assign_sub(d_a * 0.05)
  b.assign_sub(d_b * 0.05)

  if epoch % 20 == 0:
    print("EPOCH %d - MSE: %.4f - a:%.2f - b:%.2f" %(epoch, mse, a, b))

X:  [-0.20943771  1.2746525   1.213214   -0.17576952  1.876984    0.16379918
  1.082245    0.6199966  -0.44402212  1.3048344 ]
Y:  [-2.628313    1.8239574   1.6396422  -2.5273085   3.630952   -1.5086024
  1.2467351  -0.14001012 -3.3320663   1.9145031 ]
---------------------------------------------------
EPOCH 20 - MSE: 1.1415 - a:1.74 - b:-0.75
EPOCH 40 - MSE: 0.2881 - a:2.37 - b:-1.37
EPOCH 60 - MSE: 0.0728 - a:2.69 - b:-1.68
EPOCH 80 - MSE: 0.0184 - a:2.84 - b:-1.84
EPOCH 100 - MSE: 0.0046 - a:2.92 - b:-1.92
EPOCH 120 - MSE: 0.0012 - a:2.96 - b:-1.96
EPOCH 140 - MSE: 0.0003 - a:2.98 - b:-1.98
EPOCH 160 - MSE: 0.0001 - a:2.99 - b:-1.99
EPOCH 180 - MSE: 0.0000 - a:2.99 - b:-1.99
EPOCH 200 - MSE: 0.0000 - a:3.00 - b:-2.00
